### PR TITLE
docs (textinput): replace type="search" with type="text"

### PR DESCRIPTION
**Pull request by camillef**
Following https://github.com/talis/design-system/pull/20

### CODE REVIEW

**Comment by danielmatthew** [comment]
Does it show the little search widget for you?

**Comment by camillef** [comment]
> Does it show the little search widget for you?

Yup 

image

**Comment by danielmatthew** [comment]
Darn, I mean to approve and give you the joy of the merge.

**Review by danielmatthew — COMMENTED** [review]
I approve 👍

**Pull request merged**
